/*
===============================================================================
EDA: Magnitude Analysis
===============================================================================
Purpose:
    Break totals down across dimensions - customers by country and gender,
    products by category, average cost by category, revenue by category and
    by individual customer, and sold items by country.

Source:
    Extracted from EDA_Data_warehouse_project.sql - queries only, no code
    changed.
===============================================================================
*/

-- ======================================================================================
-- Magnitude
-- ======================================================================================


-- Find total customers by countries
select 
	country,
    count(customer_id) as Total_Customer
from gold.dim_customers
group by country
order by count(customer_id) desc;

-- Find total customers by gender

select 
	Customer_gender,
    count(customer_id) as Total_Customer
from gold.dim_customers
group by Customer_gender
order by count(customer_id) desc;

-- Find total products by category
select 
	Category,
    count(Product_id) as Total_products
from gold.dim_products
group by Category
order by count(Product_id) desc;

-- What is the average costs in each category?

select 
	Category,
    Round(avg(Cost),2) as Average_Costes
from  gold.dim_products 
group by category
order by   avg(Cost) desc;

-- What is the total revenue generated for each category?
select 
	p.category,
    sum(s.sales_amount) as Total_sales
from gold.fact_sales as s
left join gold.dim_products as p
on s.product_key = p.Product_key
group by p.category
order by sum(s.sales_amount) desc;

-- Find total revenue is generated by each customer

select 
	c.Customer_id, c.Customer_Firstname, c.Customer_Lastname,
    sum(s.Sales_Amount) as Total_sales
    from gold.fact_sales as s 
    left join gold.dim_customers as c
    on s.customer_key = c.customer_key
    group by c.Customer_id, c.Customer_Firstname, c.Customer_Lastname
    order by  sum(s.Sales_Amount) desc;
    

-- What is the distribution of sold items across countries?

select 
	c.country,
    sum(s.quantity) as Sold_items
from gold.fact_sales as s
left join gold.dim_customers as c
on c.customer_key = s.customer_key
group by c.country
order by  sum(s.quantity) desc ;

